
const employees = [
  {
    id: 1,
    firstName: "Aarav",
    email: "e@e.com",
    password: "123",
    taskCounts: {
      active: 2,
      newTask: 2,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        taskTitle: "Prepare Report",
        taskDescription: "Compile the monthly sales report.",
        taskDate: "2024-10-15",
        category: "Sales",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Team Meeting",
        taskDescription: "Attend the weekly status meeting.",
        taskDate: "2024-10-20",
        category: "Management",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Follow-up Client",
        taskDescription: "Check with the client about project progress.",
        taskDate: "2024-10-22",
        category: "Client Relations",
        active: false,
        newTask: true,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 2,
    firstName: "Vihaan",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "System Backup",
        taskDescription: "Backup all files and data.",
        taskDate: "2024-10-14",
        category: "IT",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Update Software",
        taskDescription: "Install the latest version of software tools.",
        taskDate: "2024-10-16",
        category: "IT",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Resolve Ticket",
        taskDescription: "Fix a user-reported bug.",
        taskDate: "2024-10-19",
        category: "Support",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Database Migration",
        taskDescription: "Migrate old database to new server.",
        taskDate: "2024-10-30",
        category: "IT",
        active: false,
        newTask: true,
        completed: false,
        failed: true,
      },
    ],
    taskCounts: {
      active: 2,
      newTask: 2,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 3,
    firstName: "Isha",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Social Media Campaign",
        taskDescription: "Launch a new campaign on social platforms.",
        taskDate: "2024-10-12",
        category: "Marketing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Design Brochure",
        taskDescription: "Create a product brochure for new clients.",
        taskDate: "2024-10-18",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
    taskCounts: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 4,
    firstName: "Riya",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Client Onboarding",
        taskDescription: "Complete onboarding of a new client.",
        taskDate: "2024-10-10",
        category: "Operations",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Training Session",
        taskDescription: "Conduct training for new hires.",
        taskDate: "2024-10-24",
        category: "HR",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Policy Review",
        taskDescription: "Review company policies and suggest updates.",
        taskDate: "2024-10-28",
        category: "HR",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
    taskCounts: {
      active: 1,
      newTask: 2,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 5,
    firstName: "Aditya",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Inventory Check",
        taskDescription: "Audit warehouse inventory.",
        taskDate: "2024-10-15",
        category: "Logistics",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Order Processing",
        taskDescription: "Process pending orders.",
        taskDate: "2024-10-18",
        category: "Sales",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Supplier Follow-up",
        taskDescription: "Follow up with suppliers for delivery.",
        taskDate: "2024-10-21",
        category: "Procurement",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Logistics Plan",
        taskDescription: "Develop a logistics plan for the next quarter.",
        taskDate: "2024-10-27",
        category: "Logistics",
        active: false,
        newTask: true,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Review Contracts",
        taskDescription: "Review supplier contracts for renewal.",
        taskDate: "2024-10-30",
        category: "Procurement",
        active: false,
        newTask: true,
        completed: false,
        failed: true,
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    email: "admin@me.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
};
